# Generated by Django 4.1.7 on 2023-02-23 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_employeewebsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dpartment',
            new_name='department',
        ),
        migrations.AlterModelTable(
            name='department',
            table='app_department',
        ),
    ]
